-- MySQL Script generated by MySQL Workbench
-- Sat Nov 22 10:15:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema publicacaoAC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema publicacaoAC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `publicacaoAC` DEFAULT CHARACTER SET utf8 ;
USE `publicacaoAC` ;

-- -----------------------------------------------------
-- Table `publicacaoAC`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicacaoAC`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicacaoAC`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicacaoAC`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(100) NOT NULL,
  `data_nasc_autor` DATE NULL,
  `email_autor` VARCHAR(100) NULL,
  `formacao_autor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicacaoAC`.`artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicacaoAC`.`artigo` (
  `id_artigo` INT NOT NULL AUTO_INCREMENT,
  `titulo_artigo` VARCHAR(255) NOT NULL,
  `data_publi_artigo` DATE NULL,
  `autor_id_autor` INT NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_artigo`, `autor_id_autor`, `categoria_id_categoria`),
  INDEX `fk_artigo_autor_idx` (`autor_id_autor` ASC) ,
  INDEX `fk_artigo_categoria1_idx` (`categoria_id_categoria` ASC) ,
  CONSTRAINT `fk_artigo_autor`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `publicacaoAC`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigo_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `publicacaoAC`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
